In [1]:
import numpy as np

### creating arrays

In [2]:
arr=np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [3]:
arr1=np.array([2,4,'a',6,8])
arr1

array(['2', '4', 'a', '6', '8'], dtype='<U11')

In [4]:
##creating twodimensional array
arr2=np.array([[1,3,5,7],[2,4,6,8]])
arr2

array([[1, 3, 5, 7],
       [2, 4, 6, 8]])

In [5]:
arr2[1]

array([2, 4, 6, 8])

In [6]:
arr2[0][2]

5

In [7]:
arr2[0:,1:3]

array([[3, 5],
       [4, 6]])

In [8]:
## creating multidimensional array
arr3=np.array([[[1,2,3],[2,4,5]],[[1,3,7],[2,5,9]],[[3,6,9],[1,3,5]]])
arr3

array([[[1, 2, 3],
        [2, 4, 5]],

       [[1, 3, 7],
        [2, 5, 9]],

       [[3, 6, 9],
        [1, 3, 5]]])

In [9]:
arr3.shape

(3, 2, 3)

In [10]:
arr3[1]

array([[1, 3, 7],
       [2, 5, 9]])

In [11]:
arr3[2]

array([[3, 6, 9],
       [1, 3, 5]])

In [12]:
##shallow and deep copy of an array
comp=[1,3,5,[2,4,6]]
comp

[1, 3, 5, [2, 4, 6]]

In [13]:
#shallow copy
a=np.copy(comp)
a

C:\Users\welcome\AppData\Local\conda\conda\envs\myenv\lib\site-packages\numpy\lib\function_base.py:792: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  return array(a, order=order, subok=subok, copy=True)


array([1, 3, 5, list([2, 4, 6])], dtype=object)

In [14]:
#deep copy
import copy
b =copy.deepcopy(comp)
b

[1, 3, 5, [2, 4, 6]]

In [15]:
print("id(a):",id(a))
print("id(b):",id(b))
print("id(comp):",id(comp))

id(a): 1930222956752
id(b): 1930222731328
id(comp): 1930218283968


In [16]:
comp[3].append(3)

In [17]:
print(comp)
print(a)
print(b)

[1, 3, 5, [2, 4, 6, 3]]
[1 3 5 list([2, 4, 6, 3])]
[1, 3, 5, [2, 4, 6]]


In [18]:
print(id(comp[3]))
print(id(a[3]))
print(id(b[3]))

1930222969984
1930222969984
1930222734464


### Array with place holders

In [19]:
## zeros
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [20]:
np.zeros([5,5])

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [21]:
## ones
np.ones(3)

array([1., 1., 1.])

In [22]:
np.ones([2,2])

array([[1., 1.],
       [1., 1.]])

In [23]:
## identity matrix
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [24]:
np.eye(3,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [25]:
## linespace
np.linspace(start=0,stop=10,num=6)

array([ 0.,  2.,  4.,  6.,  8., 10.])

In [26]:
##arange
np.arange(start=0,stop=10,step=3)

array([0, 3, 6, 9])

In [27]:
##full
np.full(shape=5,fill_value=8)

array([8, 8, 8, 8, 8])

### Random number generator 

In [28]:
#rand
np.random.rand(10)

array([0.54990898, 0.18332861, 0.18816031, 0.53046154, 0.95528247,
       0.39800048, 0.21570224, 0.86584477, 0.50314228, 0.62117886])

In [29]:
# randn
np.random.randn(10)

array([ 2.39100792,  2.12630233, -0.11034761, -1.24070871,  0.41814014,
        2.35416193, -1.24532865, -1.17261411,  0.75914123,  0.67708985])

In [30]:
np.random.randn(5)*10

array([-9.61700403,  7.38374561,  9.64740758, -0.67449845, -5.39076973])

In [31]:
#randint
np.random.randint(0,10,size=5)

array([3, 6, 5, 9, 9])

In [32]:
#choice
np.random.choice(a=10,size=3)

array([2, 8, 9])

In [33]:
np.random.choice(5,3,p=[0.1,0.5,0.3,0.03,0.07])

array([1, 4, 2])

In [34]:
list_=[3,6,4,2,7]
np.random.choice(list_,10,p=[0.3,0.2,0.4,0.01,0.09])

array([4, 4, 7, 4, 3, 6, 7, 6, 3, 4])

In [35]:
#empty
np.empty(5)

array([0.3 , 0.2 , 0.4 , 0.01, 0.09])

In [36]:
np.empty((3,4))

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [37]:
##Inspect an Array
array2=np.eye(4,5)
array2

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])

In [38]:
array2[1][1]=np.NaN
array2

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0., nan,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.]])

In [39]:
array2.shape

(4, 5)

In [40]:
array2.size

20

In [41]:
len(array2)

4

In [42]:
array2.ndim

2

In [43]:
array2.dtype

dtype('float64')

In [44]:
array2.astype(np.object).dtype

dtype('O')

In [45]:
array2.astype(np.float).dtype

dtype('float64')

### Summary statistics

In [46]:
a=[1,4,3,5,8,7,9]
b=[2,4,6,8,3,5,8]

In [47]:
np.sum(a)

37

In [48]:
np.mean(a)

5.285714285714286

In [49]:
np.median(a)

5.0

In [50]:
np.cumsum(a)

array([ 1,  5,  8, 13, 21, 28, 37], dtype=int32)

In [51]:
np.std(a)

2.657296462534039

In [52]:
np.corrcoef(a,b) #covariance matrix

array([[1.        , 0.41474761],
       [0.41474761, 1.        ]])

## Mathematical Operations 

In [53]:
a=np.array([1,2,3,4,5,6])
b=np.array([4,5,6,7,8,9])

In [54]:
np.sqrt(a)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974])

In [55]:
np.exp(b)

array([  54.59815003,  148.4131591 ,  403.42879349, 1096.63315843,
       2980.95798704, 8103.08392758])

In [56]:
np.power(a,2)

array([ 1,  4,  9, 16, 25, 36], dtype=int32)

In [57]:
np.divide(a,2)

array([0.5, 1. , 1.5, 2. , 2.5, 3. ])

In [58]:
np.log(b)

array([1.38629436, 1.60943791, 1.79175947, 1.94591015, 2.07944154,
       2.19722458])

In [59]:
np.log10(b) #log base 10 of each element in the array

array([0.60205999, 0.69897   , 0.77815125, 0.84509804, 0.90308999,
       0.95424251])

In [60]:
np.add(a,b)

array([ 5,  7,  9, 11, 13, 15])

In [61]:
np.subtract(a,b)

array([-3, -3, -3, -3, -3, -3])

In [62]:
np.multiply(a,b)

array([ 4, 10, 18, 28, 40, 54])

In [63]:
np.divide(a,b)

array([0.25      , 0.4       , 0.5       , 0.57142857, 0.625     ,
       0.66666667])

In [64]:
np.dot(a,b)  #matrix multiplication

154

In [65]:
np.dot(a.reshape(2,3),b.reshape(3,2))

array([[ 40,  46],
       [ 94, 109]])

## Array Manipulation

In [66]:
a=np.array([2,4,6,8,0])
a

array([2, 4, 6, 8, 0])

In [67]:
a[1]

4

In [68]:
a[1:4]

array([4, 6, 8])

In [69]:
a[:3]

array([2, 4, 6])

In [70]:
a[-1]

0

In [71]:
a[a>4]

array([6, 8])

In [72]:
a>3

array([False,  True,  True,  True, False])

In [73]:
arr=np.array([1,3,4,2,8,4,9,3,6,7,5])
arr

array([1, 3, 4, 2, 8, 4, 9, 3, 6, 7, 5])

In [74]:
comp=[1,2,3,5,[3,5,7,9]]
comp

[1, 2, 3, 5, [3, 5, 7, 9]]

In [75]:
np.insert(arr=arr,obj=1,values=[1,2,3])

array([1, 1, 2, 3, 3, 4, 2, 8, 4, 9, 3, 6, 7, 5])

In [76]:
comp.insert(0,[1,2])
comp

[[1, 2], 1, 2, 3, 5, [3, 5, 7, 9]]

In [77]:
np.delete(arr,[1,2,3])

array([1, 8, 4, 9, 3, 6, 7, 5])

In [78]:
arr

array([1, 3, 4, 2, 8, 4, 9, 3, 6, 7, 5])

In [79]:
np.delete(arr, np.where(arr==3), axis=0)

array([1, 4, 2, 8, 4, 9, 6, 7, 5])

In [80]:
arr

array([1, 3, 4, 2, 8, 4, 9, 3, 6, 7, 5])

In [81]:
arr1=np.array([1,2,3,4,5,6])
arr1

array([1, 2, 3, 4, 5, 6])

In [82]:
arr1.resize(2,3)
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [83]:
arr1.reshape(2,3)
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [84]:
array_=np.arange(1,5,step=0.2).reshape(4,5)
array_

array([[1. , 1.2, 1.4, 1.6, 1.8],
       [2. , 2.2, 2.4, 2.6, 2.8],
       [3. , 3.2, 3.4, 3.6, 3.8],
       [4. , 4.2, 4.4, 4.6, 4.8]])

In [85]:
array_.reshape(-1,1)[:4]

array([[1. ],
       [1.2],
       [1.4],
       [1.6]])

In [86]:
array_.T

array([[1. , 2. , 3. , 4. ],
       [1.2, 2.2, 3.2, 4.2],
       [1.4, 2.4, 3.4, 4.4],
       [1.6, 2.6, 3.6, 4.6],
       [1.8, 2.8, 3.8, 4.8]])

In [87]:
np.ravel(array_)

array([1. , 1.2, 1.4, 1.6, 1.8, 2. , 2.2, 2.4, 2.6, 2.8, 3. , 3.2, 3.4,
       3.6, 3.8, 4. , 4.2, 4.4, 4.6, 4.8])

In [88]:
array1=np.arange(1,20,2).reshape(2,5)
array2=np.arange(10,15,1).reshape(1,5)

In [89]:
print(array1)
print(array2)

[[ 1  3  5  7  9]
 [11 13 15 17 19]]
[[10 11 12 13 14]]


In [90]:
array3=np.concatenate((array1,array2),axis=0)
array3

array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19],
       [10, 11, 12, 13, 14]])

In [91]:
np.concatenate([array3,array2.T[:3]],axis=1)

array([[ 1,  3,  5,  7,  9, 10],
       [11, 13, 15, 17, 19, 11],
       [10, 11, 12, 13, 14, 12]])

In [92]:
np.vstack((array1,array2))

array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19],
       [10, 11, 12, 13, 14]])

In [93]:
np.hstack([array3,array2.T[:3]])

array([[ 1,  3,  5,  7,  9, 10],
       [11, 13, 15, 17, 19, 11],
       [10, 11, 12, 13, 14, 12]])

In [94]:
np.column_stack((array1[1],array2[0]))

array([[11, 10],
       [13, 11],
       [15, 12],
       [17, 13],
       [19, 14]])

In [95]:
np.vsplit(array1,2)

[array([[1, 3, 5, 7, 9]]), array([[11, 13, 15, 17, 19]])]

In [96]:
np.vsplit(array3,3)

[array([[1, 3, 5, 7, 9]]),
 array([[11, 13, 15, 17, 19]]),
 array([[10, 11, 12, 13, 14]])]

In [97]:
array4 = np.column_stack((array1[0], array2[0]))
array4

array([[ 1, 10],
       [ 3, 11],
       [ 5, 12],
       [ 7, 13],
       [ 9, 14]])

In [98]:
np.hsplit(array4, 2)

[array([[1],
        [3],
        [5],
        [7],
        [9]]),
 array([[10],
        [11],
        [12],
        [13],
        [14]])]